services:
  web-static:
    build:
      context: ./web-static/
      dockerfile: dockerfile
    labels:
      - "traefik.http.routers.web-static.rule=Host(`web.dai.heig-vd.ch`)"
    deploy:
      replicas: 3
    restart: unless-stopped

  web-api:
    build:
      context: ./web-api/
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.web-api.rule=Host(`api.dai.heig-vd.ch`)"
      - "traefik.http.services.web-api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.web-api.loadbalancer.sticky.cookie.name=api_session"
      - "traefik.http.services.web-api.loadbalancer.sticky.cookie.httpOnly=true"
    volumes:
      - "/var/log/traefik:/var/log"
    deploy:
      replicas: 3
    restart: unless-stopped

  traefik:
    image: traefik:v2.2
    command:
      - "--api.insecure=true" # Allow insecure connection to traefik dashboard
      - "--providers.docker" # Enable docker provider
      - "--entrypoints.web.address=:80" # Default HTTP port
      - "--accesslog=true"  # Enable access logs
      - "--log.level=DEBUG"  # Log level
      - "--accesslog.filepath=/var/logs/access.log"  # Specify if you want to log to a file
      - "--log.filepath=/var/logs/traefik/access.log"  # Specify if you want general logs to be written to a file
    ports:
      - "80:80" # Default HTTP port
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for Traefik to access Docker
      - "./logs:/var/logs" # Log files