version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  web-static:
    image: yeasy/simple-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.dai.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  web-api:
    image: yeasy/simple-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.dai.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"