services:
  web-static:
    build:
      context: ./web-static/
      dockerfile: dockerfile
    ports:
      - "8080:80"

  web-api:
    build:
      context: ./web-api/
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    restart: always
