api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/tls.yaml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
